### ISSUE TITLE
Gas amount error in SimpleCertifier

### ISSUE THREAD

**Issue by davidperrenoud** [paritytech/contracts#105]
If I import SimpleCertifier requiring Solidity 0.4.7 in a contract requiring version 0.4.19 with:

```solidity
pragma solidity ^0.4.19;

import "./base/SimpleCertifier.sol";

contract MyCertifier is SimpleCertifier {}
```

Then I get the following error:

```
Running migration: 1_initial_migration.js
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Replacing MyCertifier...
  ... 0xcc9487c6a1ded6e8496a42a40ac4db63af460ba7f259a23b1a353f81d170328f
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/Users/pea/ico-passport/ti8m-smart-contracts/node_modules/truffle/build/webpack:/~/web3/lib/web3/contract.js:147:1)
    at /Users/pea/ico-passport/ti8m-smart-contracts/node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:142:1
    at /Users/pea/ico-passport/ti8m-smart-contracts/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:89:1
    at /Users/pea/ico-passport/ti8m-smart-contracts/node_modules/truffle/build/webpack:/~/truffle-migrate/index.js:225:1
    at /Users/pea/ico-passport/ti8m-smart-contracts/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/Users/pea/ico-passport/ti8m-smart-contracts/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/pea/ico-passport/ti8m-smart-contracts/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/Users/pea/ico-passport/ti8m-smart-contracts/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/Users/pea/ico-passport/ti8m-smart-contracts/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/Users/pea/ico-passport/ti8m-smart-contracts/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
error Command failed with exit code 1.
```

But if I change the first line of SimpleCertifier:

```solidity
//pragma solidity ^0.4.7;
pragma solidity ^0.4.19;
```

Then I can deploy the contract without any problem. Any idea why this might be happening?

**Comment by davidperrenoud** [comment]
Ok, the problem was totally unrelated. Apparently, if a function is declared and inherited in a parent contract but not defined in the child contract you get this error "please check your gas amount".

In my case I had removed the empty `getData` function from Certifier in order to silence the warnings from Solidity 0.4.19, but it was then missing from SimpleCertifier. Putting it back solved the problem:

```solidity
function getData(address /* _who */, string /* _field */) public view returns (bytes32) {}
```
